# Generated by Django 5.2 on 2025-04-08 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_residents', models.IntegerField()),
                ('total_debtors', models.IntegerField(default=0)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('personal_account', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disconnected', 'Отключен'), ('archived', 'Архив')], default='active', max_length=15)),
                ('last_payment', models.DateField(blank=True, null=True)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='core.building')),
            ],
        ),
    ]
