# Generated by Django 5.2 on 2025-04-12 21:22

import core.models.building
#import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_managers_user_full_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.RemoveField(
            model_name='building',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='building',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='uploaded_by',
        ),
        #igrations.AddField(
         #   model_name='building',
        #    name='location',
       #     field=django.contrib.gis.db.models.fields.PointField(default=core.models.building.default_location, geography=True, srid=4326),
#        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelupload',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelupload',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='error_log',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
