# Generated by Django 5.2 on 2025-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='Жилой многоквартирный дом', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_apartments',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='object_type',
            field=models.CharField(default='Монолитный', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='year_built',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='iin',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
