# Generated by Django 5.2 on 2025-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_building_building_type_building_number_of_apartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='debt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='initial_term_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
