# Generated by Django 5.2 on 2025-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_debtor_debt_start_date_debtor_initial_term_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='personal_account',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
