# Generated by Django 5.2 on 2025-05-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_building_latitude_building_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='total_square',
            field=models.FloatField(default=2899.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtor',
            name='apartment_area',
            field=models.FloatField(default=69.8),
            preserve_default=False,
        ),
    ]
