# Generated by Django 5.2 on 2025-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_building_total_square_debtor_apartment_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='total_square',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
