# Generated by Django 5.2 on 2025-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_building_total_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='apartment_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
