# Generated by Django 5.2 on 2025-05-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='apart_num',
            field=models.CharField(default=49, max_length=10, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
    ]
