# Generated by Django 5.2 on 2025-05-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_debtor_apart_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.RemoveField(
            model_name='building',
            name='street',
        ),
        migrations.AddField(
            model_name='building',
            name='house',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.street'),
        ),
    ]
