# Generated by Django 5.2 on 2025-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_house_street_remove_building_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='charge_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtor',
            name='saldo_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtor',
            name='saldo_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
