# Generated by Django 5.2 on 2025-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_debtor_full_name_remove_debtor_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='pay_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_square',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
