# Generated by Django 5.2 on 2025-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_debtor_full_name_remove_debtor_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
