# Generated by Django 5.2 on 2025-06-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_debtor_full_name_remove_debtor_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_visible',
            field=models.BooleanField(
                default=True, help_text='Показывать ли объект на сайте'),
        ),
    ]
